{% set name = "array-api-extra" %}
{% set version = "0.4.0" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/array_api_extra-{{ version }}.tar.gz
  sha256: e3414742071b749922bce56171377bbca3d7696d0dab134f404bbc2875d83383

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}

test:
  imports:
    - array_api_extra
  source_files:
    - tests
  commands:
    - pip check
    - pytest -ra tests
  requires:
    - python {{ python_min }}
    - pip
    - pytest
    - array-api-strict
    - numpy

about:
  home: https://data-apis.org/array-api-extra/
  summary: Extra array functions built on top of the array API standard.
  description: Extra array functions built on top of the array API standard.
  license: MIT
  license_file: LICENSE
  doc_url: https://data-apis.org/array-api-extra/
  dev_url: https://github.com/data-apis/array-api-extra

extra:
  recipe-maintainers:
    - lucascolley
