{% set name = "array-api-extra" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/array_api_extra-{{ version }}.tar.gz
  sha256: 91b685fc90b6c5364760053127b9ee3d256caeb3563ca327c6fc98123fd5c973

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - hatchling
    - pip
  run:
    - python >=3.9

test:
  imports:
    - array_api_extra
  source_files:
    - tests
  commands:
    - pip check
    - pytest -ra tests
  requires:
    - pip
    - pytest
    - array-api-strict
    - numpy

about:
  home: https://github.com/data-apis/array-api-extra
  summary: Extra array functions built on top of the array API standard.
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/data-apis/array-api-extra

extra:
  recipe-maintainers:
    - lucascolley
