context:
  name: array-api-extra
  version: "0.10.1"
  python_min: '3.11'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/array_api_extra-${{ version }}.tar.gz
  sha256: 712ea45bd122d51c05085fc5fa30cdf66a10cc5d1af81d3e7beaff620ef1e1f2

build:
  number: 0
  noarch: python
  script: uv pip install --python ${{ PYTHON }} . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - uv
    - meson-python
  run:
    - python >=${{ python_min }}
    - array-api-compat

tests:
  - python:
      imports:
        - array_api_extra
  - script:
      - pytest -ra tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest
        - array-api-strict
        - numpy
        - hypothesis
    files:
      source:
        - tests/
        - pyproject.toml

about:
  summary: Extra array functions built on top of the array API standard.
  description: Extra array functions built on top of the array API standard.
  license: MIT
  license_file: LICENSE
  homepage: https://data-apis.org/array-api-extra/
  repository: https://github.com/data-apis/array-api-extra
  documentation: https://data-apis.org/array-api-extra/

extra:
  recipe-maintainers:
    - lucascolley
