context:
  name: array-api-extra
  version: "0.8.2"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/array_api_extra-${{ version }}.tar.gz
  sha256: 0065dc617983f521b2f094f9a2c906c6ad53e0322b579cd1773f11592c36532e

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - array-api-compat

tests:
  - python:
      imports:
        - array_api_extra
  - script:
      - pytest -ra tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest
        - array-api-strict
        - numpy
        - hypothesis
    files:
      source:
        - tests/
        - pyproject.toml

about:
  summary: Extra array functions built on top of the array API standard.
  description: Extra array functions built on top of the array API standard.
  license: MIT
  license_file: LICENSE
  homepage: https://data-apis.org/array-api-extra/
  repository: https://github.com/data-apis/array-api-extra
  documentation: https://data-apis.org/array-api-extra/

extra:
  recipe-maintainers:
    - lucascolley
