context:
  name: array-api-extra
  version: "0.7.0"
  python_min: '3.10'

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/array_api_extra-${{ version }}.tar.gz
  sha256: 68e536e43f906f368f75c1d67953b33932bedc517bd17430d4316cf32688ef8b

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
  run:
    - python >=${{ python_min }}
    - array-api-compat

tests:
  - python:
      imports:
        - array_api_extra
  - script:
      - pytest -ra tests
    requirements:
      run:
        - python ${{ python_min }}.*
        - pip
        - pytest
        - array-api-strict
        - numpy
        - hypothesis
    files:
      source:
        - tests/

about:
  summary: Extra array functions built on top of the array API standard.
  description: Extra array functions built on top of the array API standard.
  license: MIT
  license_file: LICENSE
  homepage: https://data-apis.org/array-api-extra/
  repository: https://github.com/data-apis/array-api-extra
  documentation: https://data-apis.org/array-api-extra/

extra:
  recipe-maintainers:
    - lucascolley
