# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.
# -*- mode: toml -*-

[project]
name = "array-api-extra-feedstock"
version = "3.44.9"
description = "Pixi configuration for conda-forge/array-api-extra-feedstock"
authors = ["@conda-forge/array-api-extra"]
channels = ["conda-forge"]
platforms = ['linux-64', 'osx-64', 'win-64']

[dependencies]
conda-build = ">=24.1"
conda-forge-ci-setup = "4.*"
python = "3.12.*"

[tasks]
inspect-all = "inspect_artifacts --all-packages"
build = "conda-build build recipe"
debug = "conda-build debug recipe"
"build-linux_64_" = "conda-build build recipe -m .ci_support/linux_64_.yaml --suppress-variables --clobber-file .ci_support/clobber_linux_64_.yaml"
"debug-linux_64_" = "conda-build debug recipe -m .ci_support/linux_64_.yaml"
"inspect-linux_64_" = "inspect_artifacts --recipe-dir recipe -m .ci_support/linux_64_.yaml"

[feature.smithy.dependencies]
conda-smithy = "*"

[feature.smithy.tasks]
build-locally = "python ./build-locally.py"
smithy = "conda-smithy"
rerender = "conda-smithy rerender"
lint = "conda-smithy lint recipe"

[environments]
smithy = ["smithy"]